defaults:
  - base_simulator

_target_: simulator.mujoco_simulator.MujocoSimulator
_recursive_: False
config:
  record_video: False
  marker: True
  joystick: False
  camera_follow: True
  reference_play_gate: False
  reference_play_control: SPACE
